### ISSUE TITLE
Module is broken

### ISSUE THREAD

**Issue by tlhunter** [erniehs/amaze#2]
This module relies on a module called **priorityjs**:
https://github.com/erniehs/amaze/blob/80c0ea5b4196093bba3b4b92b48ca2543da9c45d/lib/maze.js#L3

That module is erroneously listed as a dev dependency:
https://github.com/erniehs/amaze/blob/master/package.json#L36

**Comment by erniehs-zz** [comment]
doh!  let me fix that...
